### PR TITLE
Use Array Instead Of Delimiter In Validation Rules

### PR DESCRIPTION
**Pull request by amiyoghoshstar**
It is best practice to add validation rules in an array instead of using delimiters. We can use custom validation class

### CODE REVIEW

**Comment by amiyoghoshstar** [comment]
@alexeymezenin why dont you merging PRs?

**Comment by Konafets** [comment]
I doubt this is considered as best practice. It is just an alternative.

**Comment by pietrushek** [comment]
I think that this is only more elegant method... maybe sometimes more handy

**Comment by Tpojka** [comment]
> @alexeymezenin why dont you merging PRs?

PR should be rewritten following syntax and other industry standards of PSRs. Like space after comma or one space after equal arrow sign between key value pair in array. 

Aside, I agree array format is more maintainable and biggest different (and also why should be considered as better way) is that using array format rules, it is available to include custom created rule classes.

**Comment by alexeymezenin** [comment]
> I doubt this is considered as best practice. It is just an alternative.

I agree with that.

**Pull request closed without merging**
