### PR TITLE
Improved Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by binotaliu**

### CODE REVIEW

**Comment by alexeymezenin** [comment]
I wonder why have you changed words translated to Chinese to English ones (i.e. Model, Good, Bad, Accessor, etc)?

**Comment by binotaliu** [comment]
@alexeymezenin We don't use these terms in Chinese Traditional. Most case we just use English. Force translating them into Chinese make it feel weird.

**Comment by alexeymezenin** [comment]
@binotaliu thank you for the explanation. What about the translation of the words Good and Bad?

**Comment by binotaliu** [comment]
@alexeymezenin That is weird too. I checked [this translation](https://github.com/jigsawye/javascript) of [airbnb/javascript](/airbnb/javascript), they keeps Good and Bad in English.

**Comment by alexeymezenin** [comment]
Got it. Thank you for your contribution.

**Pull request merged**
