### PR TITLE
Shorter optional() in php8

### PR DESCRIPTION
**Pull request by olsza**
Since the Nullsafe operator appeared in PHP8, you can further shorten the ```optional()``` method to ```?->```  :)

### CODE REVIEW

**Comment by pietrushek** [comment]
@alexeymezenin I suggest reject this PR because PHP in 8 version for now is still low popular and common
Also @olsza made changes in 2 files (pl and en)...

**Comment by olsza** [comment]
hay @pietrushek i don't mind rejecting my PR but...
- PHP8.x is now (https://en.wikipedia.org/wiki/PHP#Release_history), and new projects are written for the latest PHP versions, not for older ones
- the topic that they are inserted in 2 files... you need to in all of them? and add in EN language add to them? because I did not find the principle of adding, but it is not a problem for me to add in other files.

**Comment by pietrushek** [comment]
I've started many projects in my job since php 8 was released but every in ver 7.x

**Comment by olsza** [comment]
ok, I start with the latest versions, but only if the hosting companies also support, and in this case PHP8 is already supported by most...
It's only a proposal, so I reckon that PR may not be accepted ;) that's what it is like in open projects.

**Review by michael-rubel — APPROVED** [review]

**Comment by pietrushek** [comment]
On packagist blog: https://blog.packagist.com/php-versions-stats-2021-1-edition
So, are you sure?

**Comment by olsza** [comment]
Ok, I'm not going to discuss it, but in general your link is for all PHP based packages in general. I gave a survey where most users use #Laravel, this is what the PR "Good Practices" is about
As for me, the topic and PR can be closed, for me it does not matter whether it will merge or not. I only made a suggestion, not to discuss.

**Comment by alexeymezenin** [comment]
Thank you for the PR. I've removed the link to your profile, sorry. I can't add it because it will be unfair to the person who originally translated the whole document to Polish. Hope for your understanding.

**Comment by olsza** [comment]
> Thank you for the PR. I've removed the link to your profile, sorry. I can't add it because it will be unfair to the person who originally translated the whole document to Polish. Hope for your understanding.

Of course I understand. That's why I gave the link as a separate commit, so that it would be easy to undo it or not commit it.

**Pull request merged**
